---
configure_dotfiles: true
configure_terminal: true

dotfiles_repo: https://github.com/colinodell/dotfiles.git
dotfiles_repo_version: main
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Projects/dotfiles
dotfiles_files:
  - .aliases
  - .exports
  - .gitconfig
  - .gitignore
  - .vimrc
  - .zshrc

apt_repositories:
  - ppa:git-core/ppa

apt_debs:
  - https://prerelease.keybase.io/keybase_amd64.deb

apt_packages:
  - curl
  - git
  - htop
  - jq
  - ncdu
  - pv
  - tree
  - unzip
  - vim
  - wget
  - zip

flatpak_packages:
  - com.google.Chrome
  - com.slack.Slack
  - com.spotify.Client
  - org.videolan.VLC

php_versions:
  - "5.6"
  - "7.1"
  - "7.2"
  - "7.3"
  - "7.4"
  - "8.0"
  - "8.1"

pip_packages:
  - name: ansible
