---
configure_dotfiles: true
configure_terminal: true

dotfiles_repo: https://github.com/colinodell/dotfiles.git
dotfiles_repo_version: main
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Projects/dotfiles
dotfiles_files:
  - .aliases
  - .exports
  - .gitconfig
  - .gitignore
  - .vimrc
  - .zshrc

apt_repositories:
  - ppa:git-core/ppa

apt_debs:
  - https://prerelease.keybase.io/keybase_amd64.deb

apt_packages:
  - curl
  - git
  - htop
  - jq
  - ncdu
  - pv
  - tree
  - unzip
  - vim
  - wget
  - zip

flatpak_packages:
  - com.google.Chrome
  - com.slack.Slack
  - com.spotify.Client
  - org.videolan.VLC

php_versions:
  - "5.6"
  - "7.1"
  - "7.2"
  - "7.3"
  - "7.4"
  - "8.0"
  - "8.1"

pip_packages:
  - name: ansible
  - name: psutil

keyboard_backlight_color: "004783"

dconf_settings:
  "/org/gnome/shell/extensions/pop-cosmic/show-applications-button": "false"
  "/org/gnome/shell/extensions/pop-cosmic/show-workspaces-button": "false"
  "/org/gnome/desktop/interface/clock-format": "'24h'"
  "/org/gnome/desktop/interface/color-scheme": "'prefer-dark'"
  "/org/gnome/desktop/interface/gtk-theme": "'Pop-dark'"
  "/org/gnome/desktop/interface/show-battery-percentage": "true"
  "/org/gnome/gedit/preferences/editor/scheme": "'pop-dark'"
  "/org/gnome/shell/extensions/dash-to-dock/manualhide": "false"
  "/org/gnome/settings-daemon/plugins/color/night-light-enabled": "true"
  "/org/gtk/Settings/FileChooser/clock-format": "'24h'"
