---
- hosts: localhost

  vars_files:
    - default.config.yml

  roles:
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']

  tasks:
    - import_tasks: tasks/terminal.yml
      when: configure_terminal
      tags: ['terminal']

    - import_tasks: tasks/packages.yml
      tags: ['packages']

    - import_tasks: tasks/php.yml
      tags: ['php']

    - import_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']
